import { ItemCategory, ItemUnlockType } from '@prisma/client';

export interface ShopItemSeed {
  id: string;
  name: string;
  description: string;
  category: ItemCategory;
  tier: number;
  cost: number;
  requiresPremium?: boolean;
  speciesLocked?: string | null;
  unlockType?: ItemUnlockType;
  imageKey: string;
  sortOrder: number;
}

/** Starter catalog for Phase 2 (~35 items). */
export const SHOP_ITEMS_SEED: ShopItemSeed[] = [
  // Pot skins
  {
    id: 'pot_terra_cotta',
    name: 'Terra cotta',
    description: 'Classic warm clay pot.',
    category: 'POT_SKIN',
    tier: 1,
    cost: 0,
    unlockType: 'DEFAULT_ITEM',
    imageKey: 'pot_terra',
    sortOrder: 1,
  },
  {
    id: 'pot_white_ceramic',
    name: 'White ceramic',
    description: 'Clean nursery style.',
    category: 'POT_SKIN',
    tier: 1,
    cost: 40,
    imageKey: 'pot_white',
    sortOrder: 2,
  },
  {
    id: 'pot_seagrass',
    name: 'Seagrass basket',
    description: 'Woven natural texture.',
    category: 'POT_SKIN',
    tier: 2,
    cost: 80,
    imageKey: 'pot_seagrass',
    sortOrder: 3,
  },
  {
    id: 'pot_mason',
    name: 'Mason jar',
    description: 'Rustic glass with twine.',
    category: 'POT_SKIN',
    tier: 2,
    cost: 70,
    imageKey: 'pot_mason',
    sortOrder: 4,
  },
  {
    id: 'pot_macrame',
    name: 'Macramé hanger',
    description: 'Hanging woven pot.',
    category: 'POT_SKIN',
    tier: 3,
    cost: 140,
    imageKey: 'pot_macrame',
    sortOrder: 5,
  },
  // Hats
  {
    id: 'hat_sun',
    name: 'Tiny sun hat',
    description: 'Shade for sunny days.',
    category: 'HAT',
    tier: 1,
    cost: 45,
    imageKey: 'hat_sun',
    sortOrder: 10,
  },
  {
    id: 'hat_flower_daisy',
    name: 'Daisy crown',
    description: 'Simple flower crown.',
    category: 'HAT',
    tier: 1,
    cost: 50,
    imageKey: 'hat_daisy',
    sortOrder: 11,
  },
  {
    id: 'hat_mushroom',
    name: 'Mushroom cap',
    description: 'Forest whimsy.',
    category: 'HAT',
    tier: 1,
    cost: 55,
    imageKey: 'hat_mushroom',
    sortOrder: 12,
  },
  {
    id: 'hat_garden_wide',
    name: 'Garden hat',
    description: 'Wide brim with ribbon.',
    category: 'HAT',
    tier: 2,
    cost: 95,
    imageKey: 'hat_garden',
    sortOrder: 13,
  },
  {
    id: 'hat_beanie',
    name: 'Green beanie',
    description: 'Cozy knit cap.',
    category: 'HAT',
    tier: 2,
    cost: 75,
    imageKey: 'hat_beanie',
    sortOrder: 14,
  },
  // Tops
  {
    id: 'top_scarf',
    name: 'Leaf scarf',
    description: 'Soft wrap for cool mornings.',
    category: 'TOP',
    tier: 1,
    cost: 60,
    imageKey: 'top_scarf',
    sortOrder: 20,
  },
  {
    id: 'top_overall',
    name: 'Garden overalls',
    description: 'Ready for messy repotting.',
    category: 'TOP',
    tier: 2,
    cost: 100,
    imageKey: 'top_overall',
    sortOrder: 21,
  },
  // Held items
  {
    id: 'held_watering_can',
    name: 'Watering can',
    description: 'Tiny silver can.',
    category: 'HELD_ITEM',
    tier: 1,
    cost: 50,
    imageKey: 'held_can',
    sortOrder: 30,
  },
  {
    id: 'held_trowel',
    name: 'Trowel',
    description: 'Pocket garden tool.',
    category: 'HELD_ITEM',
    tier: 1,
    cost: 50,
    imageKey: 'held_trowel',
    sortOrder: 31,
  },
  {
    id: 'held_lantern',
    name: 'Lantern',
    description: 'Warm evening glow.',
    category: 'HELD_ITEM',
    tier: 2,
    cost: 85,
    imageKey: 'held_lantern',
    sortOrder: 32,
  },
  {
    id: 'held_fireflies',
    name: 'Firefly jar',
    description: 'Gentle twinkle.',
    category: 'HELD_ITEM',
    tier: 3,
    cost: 120,
    imageKey: 'held_fireflies',
    sortOrder: 33,
  },
  // Glasses
  {
    id: 'glasses_round',
    name: 'Round frames',
    description: 'Scholarly spruce.',
    category: 'GLASSES',
    tier: 1,
    cost: 55,
    imageKey: 'glasses_round',
    sortOrder: 40,
  },
  {
    id: 'glasses_sun',
    name: 'Sun specs',
    description: 'Cool leaves.',
    category: 'GLASSES',
    tier: 2,
    cost: 70,
    imageKey: 'glasses_sun',
    sortOrder: 41,
  },
  // Body colors (per species — speciesLocked)
  {
    id: 'color_monstera_natural',
    name: 'Natural green',
    description: 'Default Monstera tones.',
    category: 'BODY_COLOR',
    tier: 1,
    cost: 0,
    speciesLocked: 'monstera',
    unlockType: 'DEFAULT_ITEM',
    imageKey: 'color_natural',
    sortOrder: 50,
  },
  {
    id: 'color_monstera_pastel',
    name: 'Pastel Monstera',
    description: 'Soft mint highlights.',
    category: 'BODY_COLOR',
    tier: 1,
    cost: 80,
    speciesLocked: 'monstera',
    imageKey: 'color_pastel',
    sortOrder: 51,
  },
  {
    id: 'color_cactus_natural',
    name: 'Natural cactus',
    description: 'Classic desert green.',
    category: 'BODY_COLOR',
    tier: 1,
    cost: 0,
    speciesLocked: 'cactus',
    unlockType: 'DEFAULT_ITEM',
    imageKey: 'color_natural',
    sortOrder: 52,
  },
  {
    id: 'color_cactus_vibrant',
    name: 'Vibrant cactus',
    description: 'Bold lime edges.',
    category: 'BODY_COLOR',
    tier: 1,
    cost: 90,
    speciesLocked: 'cactus',
    imageKey: 'color_vibrant',
    sortOrder: 53,
  },
  // Patterns
  {
    id: 'pattern_none',
    name: 'No pattern',
    description: 'Solid color only.',
    category: 'BODY_PATTERN',
    tier: 1,
    cost: 0,
    unlockType: 'DEFAULT_ITEM',
    imageKey: 'pattern_none',
    sortOrder: 60,
  },
  {
    id: 'pattern_spotted',
    name: 'Spotted',
    description: 'Playful dots.',
    category: 'BODY_PATTERN',
    tier: 1,
    cost: 60,
    imageKey: 'pattern_spotted',
    sortOrder: 61,
  },
  {
    id: 'pattern_variegated',
    name: 'Variegated',
    description: 'Leaf-like patches.',
    category: 'BODY_PATTERN',
    tier: 2,
    cost: 80,
    imageKey: 'pattern_variegated',
    sortOrder: 62,
  },
  // Backgrounds
  {
    id: 'bg_sunny_windowsill',
    name: 'Sunny windowsill',
    description: 'Default cozy perch.',
    category: 'BACKGROUND',
    tier: 1,
    cost: 0,
    unlockType: 'DEFAULT_ITEM',
    imageKey: 'bg_sunny',
    sortOrder: 70,
  },
  {
    id: 'bg_greenhouse',
    name: 'Greenhouse',
    description: 'Iron frames and glass.',
    category: 'BACKGROUND',
    tier: 1,
    cost: 100,
    imageKey: 'bg_greenhouse',
    sortOrder: 71,
  },
  {
    id: 'bg_rainy_window',
    name: 'Rainy window',
    description: 'Droplets on glass.',
    category: 'BACKGROUND',
    tier: 2,
    cost: 120,
    imageKey: 'bg_rain',
    sortOrder: 72,
  },
  {
    id: 'bg_forest',
    name: 'Forest floor',
    description: 'Dappled woodland light.',
    category: 'BACKGROUND',
    tier: 2,
    cost: 150,
    imageKey: 'bg_forest',
    sortOrder: 73,
  },
  // Furniture
  {
    id: 'furn_moss_patch',
    name: 'Moss patch',
    description: 'Soft green ground cover.',
    category: 'FURNITURE',
    tier: 1,
    cost: 35,
    imageKey: 'furn_moss',
    sortOrder: 80,
  },
  {
    id: 'furn_pebble',
    name: 'River pebble',
    description: 'Smooth gray stone.',
    category: 'FURNITURE',
    tier: 1,
    cost: 30,
    imageKey: 'furn_pebble',
    sortOrder: 81,
  },
  {
    id: 'furn_fairy_lights',
    name: 'Fairy lights',
    description: 'Twinkle string.',
    category: 'FURNITURE',
    tier: 2,
    cost: 90,
    imageKey: 'furn_lights',
    sortOrder: 82,
  },
  {
    id: 'furn_mushroom_cluster',
    name: 'Mushroom cluster',
    description: 'Tiny woodland fungi.',
    category: 'FURNITURE',
    tier: 2,
    cost: 75,
    imageKey: 'furn_mushroom',
    sortOrder: 83,
  },
  {
    id: 'furn_fountain',
    name: 'Stone fountain',
    description: 'Gentle drip.',
    category: 'FURNITURE',
    tier: 3,
    cost: 130,
    imageKey: 'furn_fountain',
    sortOrder: 84,
  },
];

export const BUDDY_SPECIES_SEED = [
  {
    id: 'monstera',
    displayName: 'Monty',
    description: 'Cheerful Monstera with dramatic leaves.',
    emoji: '🌿',
    unlockType: 'DEFAULT' as const,
    isDefault: true,
    sortOrder: 1,
  },
  {
    id: 'cactus',
    displayName: 'Spike',
    description: 'Stoic cactus — slow to wilt.',
    emoji: '🌵',
    unlockType: 'DEFAULT' as const,
    isDefault: true,
    sortOrder: 2,
  },
  {
    id: 'succulent',
    displayName: 'Rosie',
    description: 'Bright succulent rosette.',
    emoji: '🪴',
    unlockType: 'DEFAULT' as const,
    isDefault: true,
    sortOrder: 3,
  },
  {
    id: 'snake_plant',
    displayName: 'Sage',
    description: 'Calm snake plant stripes.',
    emoji: '🌱',
    unlockType: 'DEFAULT' as const,
    isDefault: true,
    sortOrder: 4,
  },
  {
    id: 'fern',
    displayName: 'Fernie',
    description: 'Curious fern fronds.',
    emoji: '🌿',
    unlockType: 'DEFAULT' as const,
    isDefault: true,
    sortOrder: 5,
  },
  {
    id: 'sunflower',
    displayName: 'Sunny',
    description: '+20% sunlight from care tasks.',
    emoji: '🌻',
    unlockType: 'STREAK' as const,
    unlockValue: 7,
    sortOrder: 6,
  },
  {
    id: 'bamboo',
    displayName: 'Bam',
    description: 'Streak bonus companion.',
    emoji: '🎋',
    unlockType: 'STREAK' as const,
    unlockValue: 30,
    sortOrder: 7,
  },
];

export const EQUIP_SLOT_CATEGORY: Record<string, ItemCategory> = {
  hat: 'HAT',
  top: 'TOP',
  shoes: 'SHOES',
  glasses: 'GLASSES',
  heldItem: 'HELD_ITEM',
  potSkin: 'POT_SKIN',
  bodyColor: 'BODY_COLOR',
  bodyPattern: 'BODY_PATTERN',
  companion: 'COMPANION',
  wings: 'WINGS',
};

export const TIER_MIN_STAGE: Record<number, string> = {
  1: 'SEED',
  2: 'SPROUT',
  3: 'SEEDLING',
  4: 'YOUNG_PLANT',
};

const STAGE_RANK: Record<string, number> = {
  SEED: 0,
  SPROUT: 1,
  SEEDLING: 2,
  YOUNG_PLANT: 3,
  ESTABLISHED: 4,
  ANCIENT: 5,
};

export function stageMeetsTier(growthStage: string, tier: number): boolean {
  const min = TIER_MIN_STAGE[tier] ?? 'SEED';
  return (STAGE_RANK[growthStage] ?? 0) >= (STAGE_RANK[min] ?? 0);
}
