import type { BuddyFaceExpression } from './buddyFaces';
import { BUDDY_ANIMATION_EXTENDED } from './buddyAnimationCatalogExtended';
import { BUDDY_ANIMATION_INTERACTIONS } from './buddyAnimationCatalogInteractions';

export type BuddyAnimationStatus = 'live' | 'planned';

export type BuddyPropPosition =
  | 'top-left'
  | 'top-right'
  | 'bottom-left'
  | 'bottom-right'
  | 'top'
  | 'left';

export interface BuddyAnimationDef {
  id: string;
  label: string;
  description: string;
  cssClass: string;
  face: BuddyFaceExpression;
  prop?: string;
  propPosition?: BuddyPropPosition;
  /** Second object for multi-step interactions (e.g. sandwich assembly). */
  propSecondary?: string;
  propSecondaryPosition?: BuddyPropPosition;
  /** Uses interaction keyframes on plant + props (not generic prop pop). */
  interaction?: boolean;
  durationMs?: number;
  status: BuddyAnimationStatus;
}

/**
 * Master animation catalog — work through `planned` entries and flip to `live`.
 * Companion cycles only `live` animations (see buddyCompanionAnimations.ts).
 */
export const BUDDY_ANIMATION_CATALOG: BuddyAnimationDef[] = [
  // ── Live (implemented CSS) ─────────────────────────────────────────────
  {
    id: 'bob',
    label: 'Bob',
    description: 'Gentle floating bob',
    cssClass: 'buddy-act-bob',
    face: 'happy',
    status: 'live',
  },
  {
    id: 'wave',
    label: 'Wave',
    description: 'Side-to-side wave with hand prop',
    cssClass: 'buddy-act-wave',
    face: 'cheer',
    prop: '👋',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'wink',
    label: 'Wink',
    description: 'Playful squish wink',
    cssClass: 'buddy-act-wink',
    face: 'wink',
    status: 'live',
  },
  {
    id: 'hop',
    label: 'Hop',
    description: 'Bouncy double-hop',
    cssClass: 'buddy-act-hop',
    face: 'excited',
    prop: '✨',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'smile',
    label: 'Smile',
    description: 'Warm pulsing smile',
    cssClass: 'buddy-act-smile',
    face: 'happy',
    status: 'live',
  },
  {
    id: 'sway',
    label: 'Sway',
    description: 'Slow left-right sway',
    cssClass: 'buddy-act-sway',
    face: 'cozy',
    status: 'live',
  },
  {
    id: 'nod',
    label: 'Nod',
    description: 'Encouraging yes-nod',
    cssClass: 'buddy-act-nod',
    face: 'proud',
    status: 'live',
  },
  {
    id: 'giggle',
    label: 'Giggle',
    description: 'Quick shake giggle',
    cssClass: 'buddy-act-giggle',
    face: 'giggle',
    status: 'live',
  },
  {
    id: 'bounce',
    label: 'Bounce',
    description: 'Rhythmic scale bounce',
    cssClass: 'buddy-act-bounce',
    face: 'excited',
    status: 'live',
  },
  {
    id: 'twirl',
    label: 'Twirl',
    description: 'Small happy twirl',
    cssClass: 'buddy-act-twirl',
    face: 'cheer',
    status: 'live',
  },
  {
    id: 'lean',
    label: 'Lean',
    description: 'Curious lean-in',
    cssClass: 'buddy-act-lean',
    face: 'curious',
    status: 'live',
  },
  {
    id: 'blink',
    label: 'Blink',
    description: 'Blink with tiny pause',
    cssClass: 'buddy-act-blink',
    face: 'blink',
    status: 'live',
  },
  {
    id: 'love',
    label: 'Love',
    description: 'Heartfelt sway',
    cssClass: 'buddy-act-love',
    face: 'love',
    prop: '💚',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'shy',
    label: 'Shy',
    description: 'Shy shrink and peek',
    cssClass: 'buddy-act-shy',
    face: 'shy',
    status: 'live',
  },
  {
    id: 'dance',
    label: 'Dance',
    description: 'Two-step shuffle dance',
    cssClass: 'buddy-act-dance',
    face: 'cheer',
    prop: '🎵',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'celebrate',
    label: 'Celebrate',
    description: 'Victory pop and sparkles',
    cssClass: 'buddy-act-celebrate',
    face: 'excited',
    prop: '🎉',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'float',
    label: 'Float',
    description: 'Dreamy slow float',
    cssClass: 'buddy-act-float',
    face: 'cozy',
    status: 'live',
  },
  {
    id: 'wiggle',
    label: 'Wiggle',
    description: 'Fast cute wiggle',
    cssClass: 'buddy-act-wiggle',
    face: 'giggle',
    status: 'live',
  },

  // ── Extended set (implemented in buddy-animations.css) ────────────────────
  {
    id: 'spin',
    label: 'Spin',
    description: 'Full gentle 360° spin',
    cssClass: 'buddy-act-spin',
    face: 'excited',
    status: 'live',
  },
  {
    id: 'peek',
    label: 'Peek',
    description: 'Peek from behind hands',
    cssClass: 'buddy-act-peek',
    face: 'shy',
    prop: '🫣',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'shake',
    label: 'Shake',
    description: 'Headshake no-no (playful)',
    cssClass: 'buddy-act-shake',
    face: 'surprised',
    status: 'live',
  },
  {
    id: 'stretch',
    label: 'Stretch',
    description: 'Morning stretch tall',
    cssClass: 'buddy-act-stretch',
    face: 'cozy',
    status: 'live',
  },
  {
    id: 'sleep',
    label: 'Sleep',
    description: 'Dozing droop with Zzz',
    cssClass: 'buddy-act-sleep',
    face: 'sleepy',
    prop: '💤',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'yawn',
    label: 'Yawn',
    description: 'Big cozy yawn',
    cssClass: 'buddy-act-yawn',
    face: 'sleepy',
    status: 'live',
  },
  {
    id: 'think',
    label: 'Think',
    description: 'Pondering tilt',
    cssClass: 'buddy-act-think',
    face: 'thinking',
    prop: '💭',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'surprised',
    label: 'Surprised',
    description: 'Pop-up surprise',
    cssClass: 'buddy-act-surprised',
    face: 'surprised',
    prop: '❗',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'march',
    label: 'March',
    description: 'Proud in-place march',
    cssClass: 'buddy-act-march',
    face: 'proud',
    status: 'live',
  },
  {
    id: 'flutter',
    label: 'Flutter',
    description: 'Leaf-like flutter',
    cssClass: 'buddy-act-flutter',
    face: 'happy',
    prop: '🍃',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'pulse',
    label: 'Pulse',
    description: 'Heartbeat scale pulse',
    cssClass: 'buddy-act-pulse',
    face: 'love',
    prop: '💓',
    propPosition: 'bottom-right',
    status: 'live',
  },
  {
    id: 'rain-happy',
    label: 'Rain happy',
    description: 'Joyful rain sway',
    cssClass: 'buddy-act-rain-happy',
    face: 'cheer',
    prop: '🌧️',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'sun-bask',
    label: 'Sun bask',
    description: 'Basking in sunlight',
    cssClass: 'buddy-act-sun-bask',
    face: 'cozy',
    prop: '☀️',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'water-splash',
    label: 'Water splash',
    description: 'Happy watering splash',
    cssClass: 'buddy-act-water-splash',
    face: 'excited',
    prop: '💧',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'photosynthesis',
    label: 'Photosynthesis',
    description: 'Glow-up sparkle moment',
    cssClass: 'buddy-act-photosynthesis',
    face: 'proud',
    prop: '✨',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'curious-tilt',
    label: 'Curious tilt',
    description: 'Head tilt wondering',
    cssClass: 'buddy-act-curious-tilt',
    face: 'curious',
    prop: '❓',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'proud-stand',
    label: 'Proud stand',
    description: 'Tall proud pose',
    cssClass: 'buddy-act-proud-stand',
    face: 'proud',
    status: 'live',
  },
  {
    id: 'side-step',
    label: 'Side step',
    description: 'Side-to-side steps',
    cssClass: 'buddy-act-side-step',
    face: 'happy',
    status: 'live',
  },
  {
    id: 'jelly',
    label: 'Jelly',
    description: 'Squash-and-stretch jelly',
    cssClass: 'buddy-act-jelly',
    face: 'giggle',
    status: 'live',
  },
  {
    id: 'heartbeat',
    label: 'Heartbeat',
    description: 'Double thump heartbeat',
    cssClass: 'buddy-act-heartbeat',
    face: 'love',
    status: 'live',
  },
  {
    id: 'wave-both',
    label: 'Wave both',
    description: 'Two-handed wave',
    cssClass: 'buddy-act-wave-both',
    face: 'cheer',
    prop: '🙌',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'high-five',
    label: 'High five',
    description: 'Reach for high-five',
    cssClass: 'buddy-act-high-five',
    face: 'excited',
    prop: '🖐️',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'cheer-jump',
    label: 'Cheer jump',
    description: 'Big cheer jump',
    cssClass: 'buddy-act-cheer-jump',
    face: 'cheer',
    status: 'live',
  },
  {
    id: 'snooze',
    label: 'Snooze',
    description: 'Slow snooze bob',
    cssClass: 'buddy-act-snooze',
    face: 'sleepy',
    status: 'live',
  },
  {
    id: 'greet-bow',
    label: 'Greet bow',
    description: 'Polite welcome bow',
    cssClass: 'buddy-act-greet-bow',
    face: 'shy',
    status: 'live',
  },
  {
    id: 'tickle',
    label: 'Tickle',
    description: 'Squirm tickle reaction',
    cssClass: 'buddy-act-tickle',
    face: 'giggle',
    status: 'live',
  },
  {
    id: 'listen',
    label: 'Listen',
    description: 'Attentive lean listening',
    cssClass: 'buddy-act-listen',
    face: 'curious',
    prop: '👂',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'bloom',
    label: 'Bloom',
    description: 'Flower bloom flourish',
    cssClass: 'buddy-act-bloom',
    face: 'love',
    prop: '🌸',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'water-can',
    label: 'Water can',
    description: 'Watering can tilt pour',
    cssClass: 'buddy-act-water-can',
    face: 'happy',
    prop: '🪴',
    propPosition: 'bottom-left',
    status: 'live',
  },
  {
    id: 'wind-sway',
    label: 'Wind sway',
    description: 'Wind-blown bend',
    cssClass: 'buddy-act-wind-sway',
    face: 'cozy',
    prop: '💨',
    propPosition: 'top-left',
    status: 'live',
  },
  {
    id: 'seed-friend',
    label: 'Seed friend',
    description: 'Hug tiny seed prop',
    cssClass: 'buddy-act-seed-friend',
    face: 'love',
    prop: '🌱',
    propPosition: 'bottom-right',
    status: 'live',
  },
  {
    id: 'look-around',
    label: 'Look around',
    description: 'Scan left and right',
    cssClass: 'buddy-act-look-around',
    face: 'curious',
    status: 'live',
  },
  {
    id: 'tap-dance',
    label: 'Tap dance',
    description: 'Quick tap-dance feet',
    cssClass: 'buddy-act-tap-dance',
    face: 'cheer',
    status: 'live',
  },
  {
    id: 'mirror',
    label: 'Mirror',
    description: 'Admire reflection',
    cssClass: 'buddy-act-mirror',
    face: 'proud',
    prop: '🪞',
    propPosition: 'top-right',
    status: 'live',
  },
  {
    id: 'sneeze',
    label: 'Sneeze',
    description: 'Cute sneeze jolt',
    cssClass: 'buddy-act-sneeze',
    face: 'surprised',
    prop: '🤧',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'cool-shades',
    label: 'Cool shades',
    description: 'Cool lean with shades',
    cssClass: 'buddy-act-cool-shades',
    face: 'wink',
    prop: '😎',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'rainbow',
    label: 'Rainbow',
    description: 'Arc rainbow flourish',
    cssClass: 'buddy-act-rainbow',
    face: 'excited',
    prop: '🌈',
    propPosition: 'top',
    status: 'live',
  },
  {
    id: 'team-cheer',
    label: 'Team cheer',
    description: 'Pom-pom team cheer',
    cssClass: 'buddy-act-team-cheer',
    face: 'cheer',
    prop: '📣',
    propPosition: 'top-left',
    status: 'live',
  },
  ...BUDDY_ANIMATION_EXTENDED,
  ...BUDDY_ANIMATION_INTERACTIONS,
];

export const BUDDY_LIVE_ANIMATIONS = BUDDY_ANIMATION_CATALOG.filter((a) => a.status === 'live');

export const BUDDY_PLANNED_ANIMATIONS = BUDDY_ANIMATION_CATALOG.filter(
  (a) => a.status === 'planned',
);

export function getAnimationById(id: string): BuddyAnimationDef | undefined {
  return BUDDY_ANIMATION_CATALOG.find((a) => a.id === id);
}
