import type { BuddyAnimationDef } from './buddyAnimationCatalog';

/** Object-interaction animations — plant + props move together. */
export const BUDDY_ANIMATION_INTERACTIONS: BuddyAnimationDef[] = [
  {
    id: 'coffee-drink',
    label: 'Coffee break',
    description: 'Sip a warm cup of coffee',
    cssClass: 'buddy-act-coffee-drink',
    face: 'cozy',
    prop: '☕',
    propPosition: 'bottom-right',
    propSecondary: '💨',
    propSecondaryPosition: 'top',
    interaction: true,
    durationMs: 3_200,
    status: 'live',
  },
  {
    id: 'sandwich-make',
    label: 'Make sandwich',
    description: 'Stack bread and fillings',
    cssClass: 'buddy-act-sandwich-make',
    face: 'focused',
    prop: '🍞',
    propPosition: 'bottom-left',
    propSecondary: '🧀',
    propSecondaryPosition: 'bottom-right',
    interaction: true,
    durationMs: 3_400,
    status: 'live',
  },
  {
    id: 'sandwich-eat',
    label: 'Eat sandwich',
    description: 'Munch a fresh sandwich',
    cssClass: 'buddy-act-sandwich-eat',
    face: 'giggle',
    prop: '🥪',
    propPosition: 'bottom-right',
    interaction: true,
    durationMs: 3_000,
    status: 'live',
  },
  {
    id: 'tea-sip',
    label: 'Tea time',
    description: 'Gentle tea sip',
    cssClass: 'buddy-act-tea-sip',
    face: 'cozy',
    prop: '🍵',
    propPosition: 'bottom-right',
    interaction: true,
    durationMs: 3_200,
    status: 'live',
  },
  {
    id: 'cookie-munch',
    label: 'Cookie snack',
    description: 'Nibble a cookie',
    cssClass: 'buddy-act-cookie-munch',
    face: 'happy',
    prop: '🍪',
    propPosition: 'bottom-right',
    interaction: true,
    durationMs: 2_800,
    status: 'live',
  },
  {
    id: 'smoothie-blend',
    label: 'Smoothie',
    description: 'Shake and sip a smoothie',
    cssClass: 'buddy-act-smoothie-blend',
    face: 'excited',
    prop: '🥤',
    propPosition: 'bottom-right',
    propSecondary: '🍓',
    propSecondaryPosition: 'top-left',
    interaction: true,
    durationMs: 3_200,
    status: 'live',
  },
];
