import type { BuddyAnimationDef } from './buddyAnimationCatalog';

/** Additional companion animations (appended to master catalog). */
export const BUDDY_ANIMATION_EXTENDED: BuddyAnimationDef[] = [
  { id: 'gasp', label: 'Gasp', description: 'Surprised little gasp', cssClass: 'buddy-act-gasp', face: 'surprised', status: 'live' },
  { id: 'sigh-happy', label: 'Happy sigh', description: 'Content exhale', cssClass: 'buddy-act-sigh-happy', face: 'cozy', status: 'live' },
  { id: 'content-sigh', label: 'Content sigh', description: 'Relaxed settle', cssClass: 'buddy-act-content-sigh', face: 'cozy', status: 'live' },
  { id: 'determined', label: 'Determined', description: 'Focused forward lean', cssClass: 'buddy-act-determined', face: 'proud', status: 'live' },
  { id: 'mist-leaves', label: 'Mist leaves', description: 'Gentle mist sway', cssClass: 'buddy-act-mist-leaves', face: 'happy', prop: '💧', propPosition: 'top-left', status: 'live' },
  { id: 'fertilize', label: 'Fertilize', description: 'Feeding sprinkle', cssClass: 'buddy-act-fertilize', face: 'proud', prop: '🌿', propPosition: 'top', status: 'live' },
  { id: 'repot-lift', label: 'Repot lift', description: 'Lift pot triumph', cssClass: 'buddy-act-repot-lift', face: 'excited', status: 'live' },
  { id: 'check-soil', label: 'Check soil', description: 'Peek at soil', cssClass: 'buddy-act-check-soil', face: 'curious', status: 'live' },
  { id: 'rotate-pot', label: 'Rotate pot', description: 'Turn for even light', cssClass: 'buddy-act-rotate-pot', face: 'thinking', status: 'live' },
  { id: 'hug', label: 'Hug', description: 'Self hug squeeze', cssClass: 'buddy-act-hug', face: 'love', status: 'live' },
  { id: 'thumbs-up', label: 'Thumbs up', description: 'Approval gesture', cssClass: 'buddy-act-thumbs-up', face: 'cheer', prop: '👍', propPosition: 'top-left', status: 'live' },
  { id: 'peace-sign', label: 'Peace sign', description: 'Peaceful vibe', cssClass: 'buddy-act-peace-sign', face: 'happy', prop: '✌️', propPosition: 'top-left', status: 'live' },
  { id: 'blow-kiss', label: 'Blow kiss', description: 'Kiss toward gardener', cssClass: 'buddy-act-blow-kiss', face: 'love', prop: '💋', propPosition: 'top', status: 'live' },
  { id: 'umbrella', label: 'Umbrella', description: 'Rain shelter pose', cssClass: 'buddy-act-umbrella', face: 'cozy', prop: '☂️', propPosition: 'top', status: 'live' },
  { id: 'fan-cool', label: 'Fan cool', description: 'Cooling fan sway', cssClass: 'buddy-act-fan-cool', face: 'cozy', prop: '🪭', propPosition: 'top-right', status: 'live' },
  { id: 'cozy-blanket', label: 'Cozy blanket', description: 'Snuggle wrap', cssClass: 'buddy-act-cozy-blanket', face: 'sleepy', prop: '🛋️', propPosition: 'bottom-right', status: 'live' },
  { id: 'cartwheel', label: 'Cartwheel', description: 'Playful roll', cssClass: 'buddy-act-cartwheel', face: 'excited', status: 'live' },
  { id: 'moonwalk', label: 'Moonwalk', description: 'Smooth slide back', cssClass: 'buddy-act-moonwalk', face: 'cheer', status: 'live' },
  { id: 'pop-up', label: 'Pop up', description: 'Sudden appear', cssClass: 'buddy-act-pop-up', face: 'surprised', status: 'live' },
  { id: 'hide-seek', label: 'Hide and seek', description: 'Peekaboo', cssClass: 'buddy-act-hide-seek', face: 'shy', prop: '🫣', propPosition: 'top-left', status: 'live' },
  { id: 'shiver', label: 'Shiver', description: 'Cold shiver', cssClass: 'buddy-act-shiver', face: 'surprised', status: 'live' },
  { id: 'shrug', label: 'Shrug', description: 'Playful shrug', cssClass: 'buddy-act-shrug', face: 'curious', status: 'live' },
  { id: 'salute', label: 'Salute', description: 'Proud salute', cssClass: 'buddy-act-salute', face: 'proud', status: 'live' },
  { id: 'bow-deep', label: 'Deep bow', description: 'Deep grateful bow', cssClass: 'buddy-act-bow-deep', face: 'shy', status: 'live' },
  { id: 'zoom', label: 'Zoom', description: 'Quick zoom in-out', cssClass: 'buddy-act-zoom-pulse', face: 'excited', status: 'live' },
  { id: 'sway-slow', label: 'Slow sway', description: 'Meditative sway', cssClass: 'buddy-act-sway-slow', face: 'cozy', status: 'live' },
  { id: 'pulse-soft', label: 'Soft pulse', description: 'Gentle heartbeat', cssClass: 'buddy-act-pulse-soft', face: 'love', status: 'live' },
  { id: 'leaf-wave', label: 'Leaf wave', description: 'Leaf in wind', cssClass: 'buddy-act-leaf-wave', face: 'happy', prop: '🍃', propPosition: 'top-left', status: 'live' },
  { id: 'water-drop', label: 'Water drop', description: 'Drip celebration', cssClass: 'buddy-act-water-drop', face: 'excited', prop: '💧', propPosition: 'top', status: 'live' },
  { id: 'sunbeam', label: 'Sunbeam', description: 'Bask in beam', cssClass: 'buddy-act-sunbeam', face: 'cozy', prop: '✨', propPosition: 'top', status: 'live' },
  { id: 'cloud-pass', label: 'Cloud pass', description: 'Watch cloud', cssClass: 'buddy-act-cloud-pass', face: 'cozy', prop: '☁️', propPosition: 'top-right', status: 'live' },
  { id: 'seed-plant', label: 'Plant seed', description: 'Planting motion', cssClass: 'buddy-act-seed-plant', face: 'proud', prop: '🌱', propPosition: 'bottom-left', status: 'live' },
  { id: 'prune-snip', label: 'Prune', description: 'Snip snip', cssClass: 'buddy-act-prune-snip', face: 'focused', prop: '✂️', propPosition: 'top-left', status: 'live' },
  { id: 'measure-grow', label: 'Measure', description: 'Measure height', cssClass: 'buddy-act-measure-grow', face: 'curious', status: 'live' },
  { id: 'photo-pose', label: 'Photo pose', description: 'Progress photo', cssClass: 'buddy-act-photo-pose', face: 'cheer', prop: '📷', propPosition: 'top-right', status: 'live' },
  { id: 'journal-scribble', label: 'Journal', description: 'Write notes', cssClass: 'buddy-act-journal-scribble', face: 'thinking', prop: '📝', propPosition: 'bottom-right', status: 'live' },
  { id: 'pest-watch', label: 'Pest watch', description: 'Inspect leaf', cssClass: 'buddy-act-pest-watch', face: 'curious', prop: '🔍', propPosition: 'top-right', status: 'live' },
  { id: 'humidity-happy', label: 'Humidity happy', description: 'Mist joy', cssClass: 'buddy-act-humidity-happy', face: 'happy', prop: '💨', propPosition: 'top', status: 'live' },
  { id: 'repot-dust', label: 'Repot dust', description: 'Brush off soil', cssClass: 'buddy-act-repot-dust', face: 'proud', status: 'live' },
  { id: 'propagation', label: 'Propagation', description: 'Cutting hope', cssClass: 'buddy-act-propagation', face: 'excited', prop: '🌿', propPosition: 'bottom-left', status: 'live' },
  { id: 'root-check', label: 'Root check', description: 'Gentle root peek', cssClass: 'buddy-act-root-check', face: 'thinking', status: 'live' },
  { id: 'fertilizer-shake', label: 'Fertilizer shake', description: 'Shake bottle', cssClass: 'buddy-act-fertilizer-shake', face: 'happy', status: 'live' },
  { id: 'drink-water', label: 'Drink up', description: 'Big gulp cheer', cssClass: 'buddy-act-drink-water', face: 'cheer', status: 'live' },
  { id: 'stretch-tall', label: 'Stretch tall', description: 'Reach skyward', cssClass: 'buddy-act-stretch-tall', face: 'proud', status: 'live' },
  { id: 'crouch-low', label: 'Crouch', description: 'Low inspect', cssClass: 'buddy-act-crouch-low', face: 'curious', status: 'live' },
  { id: 'spin-fast', label: 'Fast spin', description: 'Quick dizzy spin', cssClass: 'buddy-act-spin-fast', face: 'dizzy', status: 'live' },
  { id: 'wobble', label: 'Wobble', description: 'Cute wobble', cssClass: 'buddy-act-wobble', face: 'giggle', status: 'live' },
  { id: 'tip-toe', label: 'Tip toe', description: 'Sneaky steps', cssClass: 'buddy-act-tip-toe', face: 'shy', status: 'live' },
  { id: 'jump-joy', label: 'Joy jump', description: 'Single joy jump', cssClass: 'buddy-act-jump-joy', face: 'excited', status: 'live' },
  { id: 'slide-in', label: 'Slide in', description: 'Slide from side', cssClass: 'buddy-act-slide-in', face: 'happy', status: 'live' },
  { id: 'slide-out', label: 'Slide out', description: 'Peek away', cssClass: 'buddy-act-slide-out', face: 'shy', status: 'live' },
  { id: 'double-wave', label: 'Double wave', description: 'Both hands wave', cssClass: 'buddy-act-double-wave', face: 'cheer', prop: '👋', propPosition: 'top', status: 'live' },
  { id: 'clap', label: 'Clap', description: 'Happy clap', cssClass: 'buddy-act-clap', face: 'cheer', status: 'live' },
  { id: 'thinking-hard', label: 'Thinking', description: 'Deep thought', cssClass: 'buddy-act-thinking-hard', face: 'thinking', prop: '💭', propPosition: 'top-right', status: 'live' },
  { id: 'lightbulb', label: 'Idea', description: 'Aha moment', cssClass: 'buddy-act-lightbulb', face: 'excited', prop: '💡', propPosition: 'top', status: 'live' },
  { id: 'sleepy-droop', label: 'Sleepy droop', description: 'Droopy tired', cssClass: 'buddy-act-sleepy-droop', face: 'sleepy', status: 'live' },
  { id: 'wake-stretch', label: 'Wake up', description: 'Morning wake', cssClass: 'buddy-act-wake-stretch', face: 'cozy', status: 'live' },
  { id: 'night-yawn', label: 'Night yawn', description: 'Evening yawn', cssClass: 'buddy-act-night-yawn', face: 'sleepy', status: 'live' },
  { id: 'star-gaze', label: 'Star gaze', description: 'Look up dreamily', cssClass: 'buddy-act-star-gaze', face: 'cozy', prop: '⭐', propPosition: 'top', status: 'live' },
  { id: 'dew-collect', label: 'Dew collect', description: 'Catch dewdrop', cssClass: 'buddy-act-dew-collect', face: 'happy', prop: '💧', propPosition: 'bottom-right', status: 'live' },
  { id: 'shop-browse', label: 'Shop browse', description: 'Window shop', cssClass: 'buddy-act-shop-browse', face: 'curious', prop: '🛒', propPosition: 'top-right', status: 'live' },
  { id: 'quest-point', label: 'Quest', description: 'Point at quest', cssClass: 'buddy-act-quest-point', face: 'excited', prop: '🎯', propPosition: 'top-left', status: 'live' },
  { id: 'town-wave', label: 'Town wave', description: 'Wave to friends', cssClass: 'buddy-act-town-wave', face: 'cheer', prop: '🌻', propPosition: 'top', status: 'live' },
  { id: 'sunshine-send', label: 'Send sunshine', description: 'Share sunshine', cssClass: 'buddy-act-sunshine-send', face: 'love', prop: '☀️', propPosition: 'top', status: 'live' },
  { id: 'terrarium-tend', label: 'Terrarium', description: 'Tend terrarium', cssClass: 'buddy-act-terrarium-tend', face: 'cozy', status: 'live' },
  { id: 'outfit-show', label: 'Outfit show', description: 'Show off style', cssClass: 'buddy-act-outfit-show', face: 'proud', prop: '👒', propPosition: 'top', status: 'live' },
  { id: 'biome-dream', label: 'Biome dream', description: 'Dream of travel', cssClass: 'buddy-act-biome-dream', face: 'cozy', prop: '🗺️', propPosition: 'top-right', status: 'live' },
];
