import {
  authAndProtectedPathPrefixes,
  indexableMarketingRoutes,
  type MarketingRouteMeta,
} from './marketingRegistry';
import type { PublicSiteConfig } from './siteConfig';

export function defaultRobotsDirective(config: PublicSiteConfig) {
  return config.mode === 'launch' && config.marketingIndexable ? 'index,follow' : 'noindex,nofollow';
}

// AI / answer-engine crawlers, per the pre-launch SEO playbook. Answer engines
// help discovery for a beginner-help product and are allowed once the marketing
// surface is actually indexable; training/bulk crawlers stay disallowed until an
// explicit decision is made.
const AI_ANSWER_ENGINE_BOTS = ['GPTBot', 'ClaudeBot', 'PerplexityBot'];
const AI_TRAINING_BOTS = ['Google-Extended', 'CCBot'];

function emitCrawlGroup(lines: string[], userAgent: string, allowCrawl: boolean) {
  lines.push(`User-agent: ${userAgent}`);
  if (!allowCrawl) {
    lines.push('Disallow: /');
    return;
  }
  // Even allowed crawlers must stay out of auth/app paths. Per-user-agent groups
  // override the `*` group, so repeat the protected-path disallows here.
  authAndProtectedPathPrefixes.forEach((prefix) => lines.push(`Disallow: ${prefix}`));
  lines.push('Allow: /');
}

export function buildRobotsTxt(config: PublicSiteConfig) {
  const publicCrawlAllowed = config.mode !== 'private';
  const aiAnswerAllowed = config.mode === 'launch' && config.marketingIndexable;

  const lines = [
    '# Generated by the Dr. Plant pre-launch SEO gate.',
    '# Access control and noindex are the privacy controls; robots.txt only guides crawlers.',
  ];

  emitCrawlGroup(lines, '*', publicCrawlAllowed);

  lines.push('');
  AI_ANSWER_ENGINE_BOTS.forEach((bot) => emitCrawlGroup(lines, bot, aiAnswerAllowed));
  AI_TRAINING_BOTS.forEach((bot) => emitCrawlGroup(lines, bot, false));

  lines.push('', `Sitemap: ${config.canonicalBaseUrl}/sitemap.xml`, '');
  return lines.join('\n');
}

/**
 * `llms.txt` describing the product and key public URLs for AI assistants.
 * Only meaningful once the marketing surface is indexable (launch); returns an
 * empty string otherwise so the build can skip emitting it in private/teaser.
 */
export function buildLlmsTxt(config: PublicSiteConfig, routes: MarketingRouteMeta[] = indexableMarketingRoutes(config)) {
  if (!routes.length) return '';

  const lines = [
    '# Dr. Plant',
    '',
    '> AI plant doctor and houseplant care assistant for beginners. Dr. Plant helps',
    '> diagnose plant symptoms, build recovery plans, and keep houseplants on a',
    '> calmer care routine.',
    '',
    '## Key pages',
    '',
  ];

  routes
    .slice()
    .sort((a, b) => b.sitemapPriority - a.sitemapPriority)
    .forEach((route) => {
      lines.push(`- [${route.h1}](${config.canonicalBaseUrl}${route.path}): ${route.description}`);
    });

  lines.push('');
  return lines.join('\n');
}

export function buildSitemapXml(config: PublicSiteConfig, routes: MarketingRouteMeta[] = indexableMarketingRoutes(config)) {
  const urls = routes
    .map((route) => {
      const lastmod = route.lastmod ? `\n    <lastmod>${route.lastmod}</lastmod>` : '';
      return [
        '  <url>',
        `    <loc>${config.canonicalBaseUrl}${route.path}</loc>${lastmod}`,
        `    <priority>${route.sitemapPriority.toFixed(2)}</priority>`,
        '  </url>',
      ].join('\n');
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    '</urlset>',
    '',
  ]
    .filter((line) => line !== '')
    .join('\n');
}
