import {
  authAndProtectedPathPrefixes,
  indexableMarketingRoutes,
  type MarketingRouteMeta,
} from './marketingRegistry';
import type { PublicSiteConfig } from './siteConfig';

export function defaultRobotsDirective(config: PublicSiteConfig) {
  return config.mode === 'launch' && config.marketingIndexable ? 'index,follow' : 'noindex,nofollow';
}

export function buildRobotsTxt(config: PublicSiteConfig) {
  const lines = [
    '# Generated by the Dr. Plant pre-launch SEO gate.',
    '# Access control and noindex are the privacy controls; robots.txt only guides crawlers.',
    'User-agent: *',
  ];

  if (config.mode === 'private') {
    lines.push('Disallow: /');
  } else {
    authAndProtectedPathPrefixes.forEach((prefix) => lines.push(`Disallow: ${prefix}`));
    lines.push('Allow: /');
  }

  lines.push('', `Sitemap: ${config.canonicalBaseUrl}/sitemap.xml`, '');
  return lines.join('\n');
}

export function buildSitemapXml(config: PublicSiteConfig, routes: MarketingRouteMeta[] = indexableMarketingRoutes(config)) {
  const urls = routes
    .map((route) => {
      const lastmod = route.lastmod ? `\n    <lastmod>${route.lastmod}</lastmod>` : '';
      return [
        '  <url>',
        `    <loc>${config.canonicalBaseUrl}${route.path}</loc>${lastmod}`,
        `    <priority>${route.sitemapPriority.toFixed(2)}</priority>`,
        '  </url>',
      ].join('\n');
    })
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    urls,
    '</urlset>',
    '',
  ]
    .filter((line) => line !== '')
    .join('\n');
}
